// utils/suggestions.js

export const suggestions = {
    happy: [
      "Good vibes only.",
      "Happiness looks gorgeous on you.",
      "Stay close to people who feel like sunshine.",
      "Smiling for no reason — the best reason.",
      "Sunshine mixed with a little hurricane.",
      "Life is better when you’re laughing.",
      "Take time to make your soul happy.",
      "Collect moments, not things.",
      "Radiate positivity.",
      "Keep your face always toward the sunshine.",
      "Choose joy, always.",
      "Happy mind, happy life.",
      "Proof that I can do selfies better than my mood swings.",
      "Surround yourself with positive energy.",
      "Do more of what makes you happy.",
      "Nothing but blue skies ahead.",
      "Smile big, laugh often.",
      "Joy is a choice.",
      "You glow different when you’re happy.",
      "Happiness is homemade.",
      "Be the reason someone smiles today.",
      "Enjoy the little things.",
      "Don’t worry. Be happy.",
      "Happiness never goes out of style.",
      "A good day starts with a good mindset.",
      "Bloom where you are planted.",
      "Keep calm and stay happy.",
      "Your vibe attracts your tribe.",
      "Simplicity is the keynote of happiness.",
      "Celebrate every tiny victory.",
      "Let the good times roll.",
      "Happiness is the secret to all beauty.",
      "Start each day with a grateful heart.",
      "Today feels like sunshine.",
      "Be happy for this moment.",
      "Smile — it’s free therapy.",
      "Find joy in the ordinary.",
      "Chase the sun.",
      "Laugh as much as you breathe.",
      "Enjoy the now.",
      "Always choose happiness.",
      "Smiles are always in fashion.",
      "When in doubt, smile it out.",
      "You deserve to be happy.",
      "Shine from the inside out.",
      "Do small things with great love.",
      "Create your own sunshine.",
      "Your smile is your logo.",
      "A little progress each day adds up to big results.",
      "Spread love everywhere you go.",
      "Be a rainbow in someone’s cloud.",
      "Say yes to new adventures.",
      "There is beauty in simplicity.",
      "Choose kindness and laugh often.",
      "Life is short, make it sweet.",
      "Smiles are contagious.",
      "Let your light shine.",
      "Happy thoughts, happy life.",
      "Love the life you live.",
      "Life is tough, but so are you.",
      "Kindness is free, sprinkle that stuff everywhere.",
      "It’s a good day to be happy.",
      "No rain, no flowers.",
      "Peace, love, and joy.",
      "Keep your circle positive.",
      "Dream big, sparkle more.",
      "Turn the page, start a new chapter.",
      "Grow through what you go through.",
      "Live life in full bloom.",
      "Happiness blooms from within.",
      "Be your own kind of beautiful.",
      "Make today amazing.",
      "Live for the moments you can’t put into words.",
      "Stay wild, moon child.",
      "Make your soul happy.",
      "Throw kindness around like confetti.",
      "Life is beautiful.",
      "Find beauty in the small things.",
      "Seek what sets your soul on fire.",
      "Shine bright like the stars.",
      "Positive mind, positive vibes, positive life.",
      "Stay golden.",
      "Be the light.",
      "Be the best version of you.",
      "Let your happiness be louder than your fears.",
      "Laugh louder, smile bigger.",
      "More fun, less fear.",
      "Keep looking up.",
      "Celebrate yourself.",
      "You make my heart smile.",
      "Bright days ahead.",
      "Soaking up the good vibes.",
      "A grateful heart is a magnet for miracles.",
      "Keep blooming.",
      "Find your happy place.",
      "Always wear your invisible crown.",
      "Every day is a fresh start.",
      "Good energy is contagious.",
      "Living my best life."
    ],
    sad: [
      "It’s okay not to be okay.",
      "This too shall pass.",
      "Your feelings are valid.",
      "Be gentle with yourself.",
      "Take it one day at a time.",
      "Healing takes time. Be patient.",
      "You are not alone.",
      "Breathe. You’ve got this.",
      "Storms don’t last forever.",
      "Feel what you need to feel.",
      "It’s just a bad day, not a bad life.",
      "Crying is not a weakness.",
      "Let it out. Let it go.",
      "The sun will rise again.",
      "You’re stronger than you think.",
      "Broken crayons still color.",
      "It’s okay to rest.",
      "You don’t have to pretend to be strong.",
      "Take care of your heart.",
      "Better days are coming.",
      "You’re allowed to feel sad.",
      "One step at a time.",
      "Rest, but don’t quit.",
      "You matter.",
      "The darkest nights produce the brightest stars.",
      "Everything will be okay in the end.",
      "Your story isn’t over yet.",
      "Little by little, day by day.",
      "There’s hope in every sunrise.",
      "You’re not your mistakes.",
      "Your feelings are temporary.",
      "One breath at a time.",
      "Tears cleanse the soul.",
      "You’re doing your best.",
      "It’s brave to feel.",
      "Healing is not linear.",
      "Take time to heal.",
      "Let your heart breathe.",
      "Hope is never lost.",
      "Be kind to your mind.",
      "One moment can change everything.",
      "You are worthy of love.",
      "Sadness is a part of being human.",
      "You’re allowed to take up space.",
      "Your emotions do not define you.",
      "Better things are ahead.",
      "Everything happens for a reason.",
      "Even the moon goes through phases.",
      "Trust the timing of your life.",
      "Your scars are proof you survived.",
      "Your heart will smile again.",
      "Hold on. Better days are near.",
      "It’s okay to break down.",
      "Give yourself grace.",
      "You can begin again.",
      "Hope is stronger than fear.",
      "You’re not broken.",
      "Stay soft.",
      "You’re loved more than you know.",
      "Your future needs you.",
      "Every day is a second chance.",
      "Focus on the small wins.",
      "Some days, surviving is enough.",
      "Let your tears water your soul.",
      "Stay. Your story isn’t finished.",
      "There’s light inside you.",
      "You’re allowed to slow down.",
      "There is beauty in your pain.",
      "Even sadness passes.",
      "Keep your heart open.",
      "You’re not behind in life.",
      "Take your time.",
      "Grace over perfection.",
      "You are enough.",
      "The best is yet to come.",
      "Your feelings are safe here.",
      "It’s okay to ask for help.",
      "Soft hearts are strong hearts.",
      "Tomorrow is a new day.",
      "You’re not alone in this.",
      "Trust yourself.",
      "Keep breathing.",
      "It’s okay to feel lost sometimes.",
      "Your feelings deserve space.",
      "You’re more resilient than you know.",
      "Sad moments don’t define you.",
      "Don’t rush your healing.",
      "Rest your soul.",
      "Even stars can’t shine without darkness.",
      "Choose hope every day.",
      "Be proud of how far you’ve come.",
      "It’s okay to pause.",
      "You’re loved even on your worst days.",
      "Your heart will bloom again.",
      "Gentle reminders for heavy days.",
      "You’ve survived 100% of your worst days.",
      "Take comfort in small things.",
      "Your pain is valid, but so is your strength.",
      "Never stop believing in better days.",
      "You are never too much.",
      "You’re allowed to feel and heal."
    ],
    romantic: [
      "Are you a magician? Because whenever I look at you, everyone else disappears.",
      "Do you have a name? Or can I call you mine?",
        "You’re my favorite notification.",
        "Forever sounds good with you.",
        "You had me at hello.",
        "Every love story is beautiful, but ours is my favorite.",
        "You + Me = Always.",
        "In case you ever foolishly forget, I’m never not thinking of you.",
        "You’re the reason I believe in love.",
        "Home is wherever I’m with you.",
        "You make my heart smile.",
        "Falling for you every single day.",
        "I still get butterflies when I see you.",
        "You’re my sunshine on a rainy day.",
        "You’re my today and all my tomorrows.",
        "Love you to the moon and back.",
        "Can I keep you forever?",
        "With you, every moment is sweet.",
        "You make everything better.",
        "I like you more than pizza. And that’s saying a lot.",
        "You stole my heart, but I’ll let you keep it.",
        "I love you more than coffee — and that’s serious.",
        "I love being yours.",
        "Thank you for being my everything.",
        "You’re my happy place.",
        "Cuddles and kisses — that’s all I need.",
        "If I know what love is, it’s because of you.",
        "I fall in love with you every day.",
        "Your smile is my favorite.",
        "You make my heart skip a beat.",
        "You’re my sweetest addiction.",
        "Loving you is easy.",
        "You’re my kind of perfect.",
        "We’re better together.",
        "I’m much more me when I’m with you.",
        "My favorite place is inside your hug.",
        "You’re the peanut butter to my jelly.",
        "Love looks pretty on us.",
        "When I’m with you, time stands still.",
        "Forever isn’t long enough with you.",
        "You’re my once in a lifetime.",
        "I adore you.",
        "Your love is my favorite adventure.",
        "With you, I’m home.",
        "You’re the best part of my day.",
        "Love is being stupid together.",
        "Your hand fits perfectly in mine.",
        "Every day with you is my new best day.",
        "You’re my dream come true.",
        "Together is my favorite place to be.",
        "You’re the reason I smile like an idiot.",
        "My heart is and always will be yours.",
        "You’re my person.",
        "I can’t imagine life without you.",
        "You’re the cherry on top of my sundae.",
        "I love you more than yesterday, but less than tomorrow.",
        "You’re my better half.",
        "You light up my world.",
        "I’d pause my game for you.",
        "I love you more than Netflix.",
        "Can I keep you forever?",
        "My favorite place is next to you.",
        "Your love is my safe place.",
        "Your voice is my favorite sound.",
        "You’re my favorite hello and hardest goodbye.",
        "You’re my forever crush.",
        "You make my heart do a happy dance.",
        "Loving you is my favorite thing to do.",
        "You’re my love song.",
        "Your hugs are my favorite.",
        "You are my happily ever after.",
        "Love grows best with you.",
        "You’re my best decision.",
        "You’re my favorite distraction.",
        "You’re the smile I put on every day.",
        "When you hold me, I feel complete.",
        "You’re my sweetest secret.",
        "Your love feels like home.",
        "I’d choose you in every lifetime.",
        "Your eyes are my favorite view.",
        "You’re the calm in my chaos.",
        "I love the way you love me.",
        "I still fall for you every time I see you.",
        "You’re the best thing I never planned.",
        "You make ordinary moments magical.",
        "You’re my love language.",
        "You’re my ‘once upon a time’ turned into ‘forever.’",
        "You’re my favorite chapter.",
        "My heart beats for you.",
        "You’re my sweetest dream.",
        "You’re my best adventure.",
        "You’re the light of my life.",
        "Our love is my favorite fairytale.",
        "I crave you more than chocolate.",
        "You’re my soulmate.",
        "You’re my wildest dream come true.",
        "You make my world brighter.",
        "I love you endlessly.",
        "With you, I’m the best version of me."
    ],
    angry: [
      "Take a deep breath. Let that anger flow away.",
      "Sometimes it’s okay to step back and take a break.",
      "Take a deep breath. Let it go.",
  "Your peace is worth more than this.",
  "You don’t have to react to everything.",
  "Not everything deserves your energy.",
  "Let it pass. You deserve peace.",
  "Silence is sometimes the best response.",
  "Respond with calm, not chaos.",
  "Protect your energy.",
  "Choose peace over proving a point.",
  "Walk away to keep your peace.",
  "Breathe in calm, breathe out anger.",
  "You control your reaction.",
  "This moment will pass.",
  "Inner peace is your power.",
  "Sometimes letting go is the real strength.",
  "Don’t let anger steal your joy.",
  "Release it. It’s not worth it.",
  "Not every battle needs to be fought.",
  "Focus on what you can control.",
  "It’s okay to pause and cool down.",
  "You’re stronger than your anger.",
  "Peace is a choice.",
  "Your calm confuses their chaos.",
  "Stay calm, stay classy.",
  "Don’t let them get to you.",
  "Your mental peace matters more.",
  "Walk away with your head held high.",
  "Keep calm — you’re in control.",
  "Your silence is powerful.",
  "Be the bigger person.",
  "Let your peace speak louder than your anger.",
  "Your vibe attracts your tribe — choose peace.",
  "Anger fades. Regret stays. Choose wisely.",
  "Let it roll off your back.",
  "Protect your inner calm.",
  "Take time to breathe.",
  "This too shall pass.",
  "Don’t fuel the fire — let it burn out.",
  "Calm is a superpower.",
  "Be a river, not a rock."
    ],
    calm: [
      "Breathe in, breathe out. You’re okay.",
      "Peace begins with a smile.",
      "You don’t have to fix it all today.",
      "Let today be soft.",
      "You’re allowed to do nothing and just be.",
      "Wrap yourself in your own kindness.",
      "You deserve to feel safe inside your mind.",
      "One small thing at a time.",
      "Your pace is enough.",
      "It’s okay to be quiet and still.",
      "Let the world slow down with you.",
      "You’re not behind — you’re exactly where you need to be.",
      "Your mind can rest now.",
      "Light a candle. Breathe. Just exist.",
      "Sip your tea slowly. No rush.",
      "Your peace doesn’t need permission.",
      "You’re not a machine — rest is your right.",
      "You can’t pour from an empty cup.",
      "It’s okay to just listen to the rain.",
      "Your softness is your strength.",
      "Disconnect to reconnect with yourself.",
      "Right now, all you have to do is breathe.",
      "Make room for stillness in your day.",
      "Some days are for doing nothing at all.",
      "It’s okay if your only plan is to rest.",
      "Soft days heal loud minds.",
      "Quiet is good for your soul.",
      "Nothing grows forever — it’s okay to pause.",
      "You don’t need to have it all figured out today.",
      "Let your shoulders drop. Unclench your jaw.",
      "Be gentle with your thoughts.",
      "Sometimes doing less is doing more.",
      "Even your heart needs slow moments.",
      "Let your mind wander somewhere gentle.",
      "You can always come home to yourself.",
      "Hold yourself like you would hold a friend.",
      "Your worth isn’t measured by productivity.",
      "Slow mornings, warm drinks, calm heart.",
      "Take the long way home. Enjoy the view.",
      "Soak in the silence.",
      "May your mind feel like a Sunday morning.",
      "Give yourself permission to just exist.",
      "Peace looks beautiful on you.",
      "This moment doesn’t need to be perfect.",
      "You’re doing enough. You are enough.",
      "Stay present — that’s where calm lives.",
      "The world can wait while you breathe.",
      "Let your heart beat softer tonight.",
      "It’s okay to feel empty sometimes.",
      "Sometimes the best plan is no plan.",
      "You can always begin again tomorrow.",
      "Your soft moments are valid.",
      "Take a nap if you need to.",
      "Small breaths, soft mind, slow life.",
      "Let the quiet comfort you.",
      "You deserve soft blankets and gentle thoughts.",
      "Slow down to notice the little things.",
      "You’re more than what you do.",
      "Rest is a beautiful rebellion.",
      "Whisper to your worries: not today.",
      "You’re allowed to shut the world out for a while.",
      "You are a safe place for yourself.",
      "Your calm will come back. Trust it.",
      "Be so still that your soul can catch up.",
      "It’s okay to feel heavy and do nothing about it.",
      "You don’t owe the world constant motion.",
      "Put on your coziest socks. That’s enough.",
      "The day can wait. You can’t.",
      "Let the moon remind you to slow down.",
      "Unplug. Unwind. Undo the rush.",
      "Lay down your burdens, just for tonight.",
      "You deserve a soft landing.",
      "You’re allowed to be soft and strong.",
      "Let your mind drift like clouds.",
      "No pressure, only presence.",
      "You don’t need to keep up with anyone.",
      "Even your busy mind needs a hug.",
      "Let the quiet moments carry you.",
      "Your heart deserves rest too.",
      "Some days are made for slow sunsets.",
      "You can choose calm, over and over.",
      "Stay here. Stay now. Stay gentle.",
      "Life isn’t a race. Walk slowly.",
      "Your softness can move mountains too.",
      "The world is softer when you slow down.",
      "Float through the noise, find your peace.",
      "You’re safe here, just as you are.",
      "Don’t rush. Your soul knows the pace.",
      "Quiet days are good days.",
      "May you always find your calm.",
      "Your inner world deserves your love.",
      "Soft thoughts, warm heart.",
      "Rest isn’t wasted time — it’s a gift.",
      "You can breathe here.",
      "Don’t forget how to be gentle with you.",
      "Slowly, softly, gently — that’s enough.",
      "No hurry. No worry. Just be.",
      "You are not your busy mind.",
      "Let your calm be contagious.",
      "Take this moment to return to yourself."
    ],
    excited: [
        "You’re unstoppable today! Let’s go!",
        "Dream big. Start now. Crush it!",
        "Let’s goooo!",
        "Big vibes. Big dreams.",
        "Can’t calm down, don’t want to.",
        "Too hyped to sit still.",
        "Energy unmatched.",
        "This is my glow-up era.",
        "Good energy attracts good things.",
        "Today’s vibe: unstoppable.",
        "Catch flights, not feelings — but maybe both.",
        "Excitement level: 1000%",
        "The future looks fun.",
        "Manifesting magic every day.",
        "Living my dream out loud.",
        "This is what hype feels like.",
        "Adrenaline mode: ON.",
        "Making moves and good memories.",
        "I’m the energy I want to attract.",
        "Ready for whatever comes next.",
        "So ready. So set. So GO.",
        "Can’t stop, won’t stop.",
        "Fuelled by big dreams and coffee.",
        "High on life right now.",
        "Living for the thrill of it.",
        "Too excited to be chill.",
        "Adventure: loading…",
        "I’m the plot twist.",
        "Feeling so alive right now.",
        "This is what I’ve been waiting for.",
        "Big plans, bigger energy.",
        "Turn the volume UP.",
        "The vibe is: electric.",
        "Life’s too short not to get hyped.",
        "Overthinking? Nope, just doing.",
        "Ready, steady, go shine.",
        "Every day’s a new adventure.",
        "My moment is now.",
        "Unstoppable energy.",
        "New day, new opportunities.",
        "Leveling up, every day.",
        "Bring on the good chaos.",
        "Stay wild, stay excited.",
        "Adventure is my middle name.",
        "I’m here for a good time AND a long time.",
        "Caffeine & confidence — let’s go.",
        "Ready to take over the world (again).",
        "This energy is contagious.",
        "The hype is real.",
        "I thrive on excitement.",
        "Blessed & busy & buzzing.",
        "Life’s a party — show up loud.",
        "Passion mode: activated.",
        "Make it happen. Make it loud.",
        "This is your green light.",
        "Bring your dreams to the table.",
        "I’m not calm — I’m excited.",
        "Too many dreams to sit still.",
        "My energy speaks before I do.",
        "You can’t dim this shine.",
        "Nothing can dull my vibe today.",
        "Running on pure excitement.",
        "Do it with excitement or not at all.",
        "Big goals, bigger grin.",
        "The grind is my groove.",
        "Keep your energy wild.",
        "This is your sign: go for it!",
        "Be your own hype person.",
        "Jump in, the future’s fun.",
        "Overflowing with good vibes.",
        "Excitement looks good on me.",
        "Wild hearts can’t be tamed.",
        "Got dreams? Let’s chase them.",
        "Stay excited for the unknown.",
        "Life’s too short to stay calm.",
        "Turn your passion all the way up.",
        "I’m ready for my next big thing.",
        "Good things are coming fast.",
        "Every moment is an opportunity.",
        "Go after what sets your soul on fire.",
        "No chill, just thrill.",
        "Keep moving forward with fire.",
        "I’m exactly where the fun is.",
        "The adventure starts now.",
        "Sparkle like you mean it.",
        "Momentum is my middle name.",
        "Keep chasing what excites you.",
        "Be bold. Be loud. Be unstoppable.",
        "Energy so good it’s contagious.",
        "Catch me living my best life.",
        "Too busy living to worry.",
        "Be the buzz in the room.",
        "Vibe check: electric.",
        "Today’s mood: do it all.",
        "Shaking things up, one dream at a time.",
        "Bigger dreams, bigger energy.",
        "Thrilled for what’s next.",
        "No fear, just fun.",
        "I’m ready. Let’s make it happen."
      ],
  };
  